[package]
name = "code_parser"
version = "0.1.0"
edition = "2025"

[lib]
crate-type = ["cdylib"]  

[dependencies]
tree-sitter = "0.20.10"  
tree-sitter-python = "0.20.4"
tree-sitter-javascript = "0.20.3"
pyo3 = { version = "0.18.3", features = ["extension-module"] }
